services:
  frontend:
    build: ./frontend
    image: playthemood-frontend:latest
    ports:
      - "5000:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    image: playthemood-backend:latest
    ports:
      - "5000:5000"